/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Rectangle;

/**
 *
 * @author felipe
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
    
    public void centralizeFrame(){
      int x, y; // dimensões da tela
      Rectangle scr = this.getGraphicsConfiguration().getBounds();
      Rectangle form = this.getBounds();
      x = (int) (scr.getWidth() - form.getWidth())/2;
      y = (int) (scr.getHeight()- form.getHeight())/2;
      this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuProduto = new javax.swing.JMenu();
        jMenuCadastroProdutos = new javax.swing.JMenuItem();
        jMenuVenda = new javax.swing.JMenu();
        jMenuHistoricoVendas = new javax.swing.JMenuItem();
        jMenuNovaVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuProduto.setText("Produtos");

        jMenuCadastroProdutos.setText("Cadastro Produtos");
        jMenuCadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroProdutosActionPerformed(evt);
            }
        });
        jMenuProduto.add(jMenuCadastroProdutos);

        jMenuBar1.add(jMenuProduto);

        jMenuVenda.setText("Venda");

        jMenuHistoricoVendas.setText("Historico de Vendas");
        jMenuHistoricoVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHistoricoVendasActionPerformed(evt);
            }
        });
        jMenuVenda.add(jMenuHistoricoVendas);

        jMenuNovaVenda.setText("Nova Venda");
        jMenuVenda.add(jMenuNovaVenda);

        jMenuBar1.add(jMenuVenda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroProdutosActionPerformed
        // TODO add your handling code here:
        CadastroProdutos cadprod = new CadastroProdutos();
        cadprod.show();
    }//GEN-LAST:event_jMenuCadastroProdutosActionPerformed

    private void jMenuHistoricoVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHistoricoVendasActionPerformed
        // TODO add your handling code here:
        CadastroVendas cadven = new CadastroVendas();
        cadven.show();
    }//GEN-LAST:event_jMenuHistoricoVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadastroProdutos;
    private javax.swing.JMenuItem jMenuHistoricoVendas;
    private javax.swing.JMenuItem jMenuNovaVenda;
    private javax.swing.JMenu jMenuProduto;
    private javax.swing.JMenu jMenuVenda;
    // End of variables declaration//GEN-END:variables
}
