/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import Persistence.ItemVendaDAO;
import Persistence.VendaDAO;
import Pojo.ItemVenda;
import Pojo.Produto;
import Pojo.Venda;
import java.awt.Rectangle;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
//import java.awt.Component;
//import javax.swing.DefaultListCellRenderer;
//import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.Data;

/**
 *
 * @author felipe
 */
public class VendaIT extends javax.swing.JFrame {


    
    
    
    /**
     * Creates new form Venda
     */
    public VendaIT() {
        initComponents();
    }
    
    public void centralizeFrame(){
      int x, y; // dimensões da tela
      Rectangle scr = this.getGraphicsConfiguration().getBounds();
      Rectangle form = this.getBounds();
      x = (int) (scr.getWidth() - form.getWidth())/2;
      y = (int) (scr.getHeight()- form.getHeight())/2;
      this.setLocation(x, y);
    }
    
    // Adiciona os itens na tabela do Frame 
    public void AdicionaTabela() {
        String a = jTextFieldCodProduto.getText();
        String b = jTextFieldQtdProduto.getText();
        String c = jTextFieldUnitPrice.getText().replaceAll(",", ".");
        String d = jTextFieldCodigoPedido.getText();
        int CodProduto = Integer.parseInt(a);
        int QtdProduto = Integer.parseInt(b);
        double unitPrice = Double.parseDouble(c);
        int CodigoPedido = Integer.parseInt(d);
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.addRow(new Object[]{CodigoPedido, CodProduto, QtdProduto, unitPrice, (QtdProduto * unitPrice)});
        // final da parte que adiciona na Tabela
    }

    // Indice da tabela começa em 0 então faço -1 para, o usuario digitar de 1 .... n 
    // na hora de excluir um item do Pedido 
    public void RemoveItem(int id) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        try{
        modelo.removeRow(id-1);
        } catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "A linha já foi Excluída ou não existe!");
        }
    }    
   
    // Busca o proximo ID de venda na tabela de pedidos do banco de dados 
    public int geraCodigoVenda(){
       int max_id = new VendaDAO().max_id();
       return max_id; 
    }
    
    // Gera uma string da data corrente para jogar no TextField 
    public String CurrentData (){
       
       Date date = new Date();       
       SimpleDateFormat formatador = new SimpleDateFormat();
       String data = formatador.format(date);       
       return data;    
    }
    
    public double calcula_valor_total(int cod_venda){
      double vlr_total = new ItemVendaDAO().sum_id(cod_venda);
      return vlr_total;
    }
    
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNaoEditaveis = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigoPedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jButtonGerarSequencial = new javax.swing.JButton();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanelEditaveis = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCodProduto = new javax.swing.JTextField();
        jTextFieldQtdProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUnitPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonExcluirItem = new javax.swing.JButton();
        jTextFieldExcluirItem = new javax.swing.JTextField();
        jButtonFecharVenda = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Codigo Venda");

        jTextFieldCodigoPedido.setEditable(false);
        jTextFieldCodigoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoPedidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Data");

        jTextFieldData.setEditable(false);
        jTextFieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataActionPerformed(evt);
            }
        });

        jButtonGerarSequencial.setText("GerarNum");
        jButtonGerarSequencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarSequencialActionPerformed(evt);
            }
        });

        jTextFieldValorTotal.setEditable(false);

        jLabel7.setText("Valor Total");

        javax.swing.GroupLayout jPanelNaoEditaveisLayout = new javax.swing.GroupLayout(jPanelNaoEditaveis);
        jPanelNaoEditaveis.setLayout(jPanelNaoEditaveisLayout);
        jPanelNaoEditaveisLayout.setHorizontalGroup(
            jPanelNaoEditaveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNaoEditaveisLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelNaoEditaveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelNaoEditaveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonGerarSequencial)
                        .addGroup(jPanelNaoEditaveisLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelNaoEditaveisLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelNaoEditaveisLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanelNaoEditaveisLayout.setVerticalGroup(
            jPanelNaoEditaveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNaoEditaveisLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanelNaoEditaveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelNaoEditaveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonGerarSequencial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanelNaoEditaveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(93, 93, 93))
        );

        jPanelEditaveis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Pedido", "Codigo Produto", "Qtd", "Unit Price", "Valor Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanelEditaveis.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 480, 275));

        jLabel4.setText("Itens da Venda");
        jPanelEditaveis.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel5.setText("Codigo Produto");
        jPanelEditaveis.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 120, 20));

        jTextFieldCodProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodProdutoActionPerformed(evt);
            }
        });
        jPanelEditaveis.add(jTextFieldCodProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 44, -1));
        jPanelEditaveis.add(jTextFieldQtdProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 45, -1));

        jLabel6.setText("Qtd");
        jPanelEditaveis.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 40, -1));

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanelEditaveis.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 80, -1));

        jLabel3.setText("Unit Price");
        jPanelEditaveis.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 80, -1));

        jTextFieldUnitPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUnitPriceActionPerformed(evt);
            }
        });
        jPanelEditaveis.add(jTextFieldUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 50, -1));

        jLabel8.setText("Cancela Item: ");
        jPanelEditaveis.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 80, -1));

        jButtonExcluirItem.setText("Excluir");
        jButtonExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirItemActionPerformed(evt);
            }
        });
        jPanelEditaveis.add(jButtonExcluirItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 70, -1));
        jPanelEditaveis.add(jTextFieldExcluirItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 50, -1));

        jButtonFecharVenda.setText("Fechar Venda");
        jButtonFecharVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharVendaActionPerformed(evt);
            }
        });
        jPanelEditaveis.add(jButtonFecharVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, -1, -1));

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanelNaoEditaveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanelEditaveis, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(710, 710, 710)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanelNaoEditaveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelEditaveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSalvar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodProdutoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
//        Venda nova = new Venda();
//        
//        VendaDAO dao = new VendaDAO();
//        
//        nova.setCodigoPedido(dao.max_id());
//        nova.setData();
//        
//        try {
//            dao.inserir(dao);
//        } catch (SQLException ex) {
//            Logger.getLogger(Venda.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        this.AdicionaTabela();
//        jTextField2.setText(this.CurrentData());      
//        String ID = String.valueOf(this.geraCodigoVenda()); // alterar o valor do valueof p/ this.geracodigo()
//        jTextField1.setText(ID);
        ItemVenda item = new ItemVenda();
        ItemVendaDAO dao = new ItemVendaDAO();
        
        
        item.setCodigoProduto(Integer.parseInt(jTextFieldCodProduto.getText()));
        item.setQuantidade(Integer.parseInt(jTextFieldQtdProduto.getText()));
        item.setUnitprice(Double.parseDouble(jTextFieldUnitPrice.getText().replaceAll(",", ".")));
        double vlr_total_item = item.getQuantidade()*item.getUnitprice();
        item.setPriceItem(vlr_total_item);
        try {
            dao.inserir(item, Integer.parseInt(jTextFieldCodigoPedido.getText()));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "itens de venda não computados.\n" + ex.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUnitPriceActionPerformed

    private void jButtonExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirItemActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jTextFieldExcluirItem.getText());
        this.RemoveItem(id);
    }//GEN-LAST:event_jButtonExcluirItemActionPerformed

    private void jTextFieldCodigoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoPedidoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldCodigoPedidoActionPerformed

    private void jTextFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextFieldDataActionPerformed

    private void jButtonGerarSequencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarSequencialActionPerformed
        // TODO add your handling code here:
        jTextFieldData.setText(this.CurrentData());      
        String ID = String.valueOf(this.geraCodigoVenda()); // alterar o valor do valueof p/ this.geracodigo()
        jTextFieldCodigoPedido.setText(ID);
        VendaDAO vdao = new VendaDAO();
        Venda nova = new Venda(this.geraCodigoVenda());
        nova.setData(this.CurrentData());
        
        try {
            vdao.inserir(nova);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Venda não inciada.\n" + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonGerarSequencialActionPerformed

    private void jButtonFecharVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharVendaActionPerformed
        // TODO add your handling code here:
        Venda n1 = new Venda(Integer.parseInt(jTextFieldCodigoPedido.getText()));
        n1.setData(this.CurrentData());
        n1.setVlr_total(this.calcula_valor_total(Integer.parseInt(jTextFieldCodigoPedido.getText())));
        
        VendaDAO vdao2 = new VendaDAO();
        try {
            vdao2.atualizar(Integer.parseInt(jTextFieldCodigoPedido.getText()), n1);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Venda não Finalizada.\n" + ex.getMessage());
        }
        
        jTextFieldValorTotal.setText(String.valueOf(this.calcula_valor_total(n1.getCodigoPedido())));
        
    }//GEN-LAST:event_jButtonFecharVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaIT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluirItem;
    private javax.swing.JButton jButtonFecharVenda;
    private javax.swing.JButton jButtonGerarSequencial;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelEditaveis;
    private javax.swing.JPanel jPanelNaoEditaveis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCodProduto;
    private javax.swing.JTextField jTextFieldCodigoPedido;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldExcluirItem;
    private javax.swing.JTextField jTextFieldQtdProduto;
    private javax.swing.JTextField jTextFieldUnitPrice;
    private javax.swing.JTextField jTextFieldValorTotal;
    // End of variables declaration//GEN-END:variables
}
